// Code generated by protoc-gen-go. DO NOT EDIT.
// source: role.proto

package tapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 获取企业中角色下的员工列表请求参数
type RoleSimplelistRequest struct {
	// 角色ID
	RoleId int64 `protobuf:"varint,1,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
	// 分页大小
	Size int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	// 分页偏移
	Offset int64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *RoleSimplelistRequest) Reset()                    { *m = RoleSimplelistRequest{} }
func (m *RoleSimplelistRequest) String() string            { return proto.CompactTextString(m) }
func (*RoleSimplelistRequest) ProtoMessage()               {}
func (*RoleSimplelistRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RoleSimplelistRequest) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleSimplelistRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RoleSimplelistRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type RoleSimplelistResponseResultListEmpSimpleList struct {
	Userid string `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *RoleSimplelistResponseResultListEmpSimpleList) Reset() {
	*m = RoleSimplelistResponseResultListEmpSimpleList{}
}
func (m *RoleSimplelistResponseResultListEmpSimpleList) String() string {
	return proto.CompactTextString(m)
}
func (*RoleSimplelistResponseResultListEmpSimpleList) ProtoMessage() {}
func (*RoleSimplelistResponseResultListEmpSimpleList) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{1}
}

func (m *RoleSimplelistResponseResultListEmpSimpleList) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type RoleSimplelistResponseResultList struct {
	EmpSimpleList []*RoleSimplelistResponseResultListEmpSimpleList `protobuf:"bytes,1,rep,name=emp_simple_list,json=empSimpleList" json:"emp_simple_list,omitempty"`
}

func (m *RoleSimplelistResponseResultList) Reset()         { *m = RoleSimplelistResponseResultList{} }
func (m *RoleSimplelistResponseResultList) String() string { return proto.CompactTextString(m) }
func (*RoleSimplelistResponseResultList) ProtoMessage()    {}
func (*RoleSimplelistResponseResultList) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{2}
}

func (m *RoleSimplelistResponseResultList) GetEmpSimpleList() []*RoleSimplelistResponseResultListEmpSimpleList {
	if m != nil {
		return m.EmpSimpleList
	}
	return nil
}

type RoleSimplelistResponseResult struct {
	HasMore bool                              `protobuf:"varint,1,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	List    *RoleSimplelistResponseResultList `protobuf:"bytes,2,opt,name=list" json:"list,omitempty"`
}

func (m *RoleSimplelistResponseResult) Reset()                    { *m = RoleSimplelistResponseResult{} }
func (m *RoleSimplelistResponseResult) String() string            { return proto.CompactTextString(m) }
func (*RoleSimplelistResponseResult) ProtoMessage()               {}
func (*RoleSimplelistResponseResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *RoleSimplelistResponseResult) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

func (m *RoleSimplelistResponseResult) GetList() *RoleSimplelistResponseResultList {
	if m != nil {
		return m.List
	}
	return nil
}

type RoleSimplelist struct {
	Result *RoleSimplelistResponseResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *RoleSimplelist) Reset()                    { *m = RoleSimplelist{} }
func (m *RoleSimplelist) String() string            { return proto.CompactTextString(m) }
func (*RoleSimplelist) ProtoMessage()               {}
func (*RoleSimplelist) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *RoleSimplelist) GetResult() *RoleSimplelistResponseResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// 获取企业中角色下的员工列表响应参数
type RoleSimplelistResponse struct {
	DingtalkCorpRoleSimplelistResponse *RoleSimplelist `protobuf:"bytes,1,opt,name=dingtalk_corp_role_simplelist_response,json=dingtalkCorpRoleSimplelistResponse" json:"dingtalk_corp_role_simplelist_response,omitempty"`
	ErrorResponse                      *TopApiResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse" json:"error_response,omitempty"`
}

func (m *RoleSimplelistResponse) Reset()                    { *m = RoleSimplelistResponse{} }
func (m *RoleSimplelistResponse) String() string            { return proto.CompactTextString(m) }
func (*RoleSimplelistResponse) ProtoMessage()               {}
func (*RoleSimplelistResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *RoleSimplelistResponse) GetDingtalkCorpRoleSimplelistResponse() *RoleSimplelist {
	if m != nil {
		return m.DingtalkCorpRoleSimplelistResponse
	}
	return nil
}

func (m *RoleSimplelistResponse) GetErrorResponse() *TopApiResponse {
	if m != nil {
		return m.ErrorResponse
	}
	return nil
}

// 获取企业角色列表请求参数
type RoleListRequest struct {
	// 分页大小
	Size int64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	// 分页偏移
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *RoleListRequest) Reset()                    { *m = RoleListRequest{} }
func (m *RoleListRequest) String() string            { return proto.CompactTextString(m) }
func (*RoleListRequest) ProtoMessage()               {}
func (*RoleListRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *RoleListRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *RoleListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type RoleListResultListRoleGroupsRolesBody struct {
	Id       int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
}

func (m *RoleListResultListRoleGroupsRolesBody) Reset()         { *m = RoleListResultListRoleGroupsRolesBody{} }
func (m *RoleListResultListRoleGroupsRolesBody) String() string { return proto.CompactTextString(m) }
func (*RoleListResultListRoleGroupsRolesBody) ProtoMessage()    {}
func (*RoleListResultListRoleGroupsRolesBody) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{7}
}

func (m *RoleListResultListRoleGroupsRolesBody) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RoleListResultListRoleGroupsRolesBody) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type RoleListResultListRoleGroupsRoles struct {
	Roles []*RoleListResultListRoleGroupsRolesBody `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (m *RoleListResultListRoleGroupsRoles) Reset()         { *m = RoleListResultListRoleGroupsRoles{} }
func (m *RoleListResultListRoleGroupsRoles) String() string { return proto.CompactTextString(m) }
func (*RoleListResultListRoleGroupsRoles) ProtoMessage()    {}
func (*RoleListResultListRoleGroupsRoles) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{8}
}

func (m *RoleListResultListRoleGroupsRoles) GetRoles() []*RoleListResultListRoleGroupsRolesBody {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RoleListResultListRoleGroups struct {
	Roles     *RoleListResultListRoleGroupsRoles `protobuf:"bytes,1,opt,name=roles" json:"roles,omitempty"`
	GroupName string                             `protobuf:"bytes,2,opt,name=group_name,json=groupName" json:"group_name,omitempty"`
}

func (m *RoleListResultListRoleGroups) Reset()                    { *m = RoleListResultListRoleGroups{} }
func (m *RoleListResultListRoleGroups) String() string            { return proto.CompactTextString(m) }
func (*RoleListResultListRoleGroups) ProtoMessage()               {}
func (*RoleListResultListRoleGroups) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *RoleListResultListRoleGroups) GetRoles() *RoleListResultListRoleGroupsRoles {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *RoleListResultListRoleGroups) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type RoleListResultList struct {
	RoleGroups []*RoleListResultListRoleGroups `protobuf:"bytes,1,rep,name=role_groups,json=roleGroups" json:"role_groups,omitempty"`
}

func (m *RoleListResultList) Reset()                    { *m = RoleListResultList{} }
func (m *RoleListResultList) String() string            { return proto.CompactTextString(m) }
func (*RoleListResultList) ProtoMessage()               {}
func (*RoleListResultList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *RoleListResultList) GetRoleGroups() []*RoleListResultListRoleGroups {
	if m != nil {
		return m.RoleGroups
	}
	return nil
}

type RoleListResult struct {
	HasMore string              `protobuf:"bytes,1,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	List    *RoleListResultList `protobuf:"bytes,2,opt,name=list" json:"list,omitempty"`
}

func (m *RoleListResult) Reset()                    { *m = RoleListResult{} }
func (m *RoleListResult) String() string            { return proto.CompactTextString(m) }
func (*RoleListResult) ProtoMessage()               {}
func (*RoleListResult) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *RoleListResult) GetHasMore() string {
	if m != nil {
		return m.HasMore
	}
	return ""
}

func (m *RoleListResult) GetList() *RoleListResultList {
	if m != nil {
		return m.List
	}
	return nil
}

type RoleList struct {
	Result *RoleListResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *RoleList) Reset()                    { *m = RoleList{} }
func (m *RoleList) String() string            { return proto.CompactTextString(m) }
func (*RoleList) ProtoMessage()               {}
func (*RoleList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *RoleList) GetResult() *RoleListResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// 获取企业角色列表响应参数
type RoleListResponse struct {
	DingtalkCorpRoleListResponse *RoleList       `protobuf:"bytes,1,opt,name=dingtalk_corp_role_list_response,json=dingtalkCorpRoleListResponse" json:"dingtalk_corp_role_list_response,omitempty"`
	ErrorResponse                *TopApiResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse" json:"error_response,omitempty"`
}

func (m *RoleListResponse) Reset()                    { *m = RoleListResponse{} }
func (m *RoleListResponse) String() string            { return proto.CompactTextString(m) }
func (*RoleListResponse) ProtoMessage()               {}
func (*RoleListResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *RoleListResponse) GetDingtalkCorpRoleListResponse() *RoleList {
	if m != nil {
		return m.DingtalkCorpRoleListResponse
	}
	return nil
}

func (m *RoleListResponse) GetErrorResponse() *TopApiResponse {
	if m != nil {
		return m.ErrorResponse
	}
	return nil
}

// 企业在做企业员工管理的时候，需要对部分员工进行角色分类，该接口可以批量为员工增加角色信息
// 请求参数
type AddRolesForEmpsRequest struct {
	// 角色id list
	RolelidList []int64 `protobuf:"varint,1,rep,packed,name=rolelid_list,json=rolelidList" json:"rolelid_list,omitempty"`
	// 员工id list
	UseridList []string `protobuf:"bytes,2,rep,name=userid_list,json=useridList" json:"userid_list,omitempty"`
}

func (m *AddRolesForEmpsRequest) Reset()                    { *m = AddRolesForEmpsRequest{} }
func (m *AddRolesForEmpsRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRolesForEmpsRequest) ProtoMessage()               {}
func (*AddRolesForEmpsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *AddRolesForEmpsRequest) GetRolelidList() []int64 {
	if m != nil {
		return m.RolelidList
	}
	return nil
}

func (m *AddRolesForEmpsRequest) GetUseridList() []string {
	if m != nil {
		return m.UseridList
	}
	return nil
}

type DingOpenResponse struct {
	DingOpenErrcode int64  `protobuf:"varint,1,opt,name=ding_open_errcode,json=dingOpenErrcode" json:"ding_open_errcode,omitempty"`
	ErrorMsg        string `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
	Success         bool   `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
}

func (m *DingOpenResponse) Reset()                    { *m = DingOpenResponse{} }
func (m *DingOpenResponse) String() string            { return proto.CompactTextString(m) }
func (*DingOpenResponse) ProtoMessage()               {}
func (*DingOpenResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *DingOpenResponse) GetDingOpenErrcode() int64 {
	if m != nil {
		return m.DingOpenErrcode
	}
	return 0
}

func (m *DingOpenResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *DingOpenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddRolesForEmps struct {
	Result *DingOpenResponse `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *AddRolesForEmps) Reset()                    { *m = AddRolesForEmps{} }
func (m *AddRolesForEmps) String() string            { return proto.CompactTextString(m) }
func (*AddRolesForEmps) ProtoMessage()               {}
func (*AddRolesForEmps) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *AddRolesForEmps) GetResult() *DingOpenResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

// 企业在做企业员工管理的时候，需要对部分员工进行角色分类，该接口可以批量为员工增加角色信息
// 响应参数
type AddRolesForEmpsResponse struct {
	DingtalkCorpRoleAddrolesforempsResponse *AddRolesForEmps `protobuf:"bytes,1,opt,name=dingtalk_corp_role_addrolesforemps_response,json=dingtalkCorpRoleAddrolesforempsResponse" json:"dingtalk_corp_role_addrolesforemps_response,omitempty"`
	ErrorResponse                           *TopApiResponse  `protobuf:"bytes,2,opt,name=error_response,json=errorResponse" json:"error_response,omitempty"`
}

func (m *AddRolesForEmpsResponse) Reset()                    { *m = AddRolesForEmpsResponse{} }
func (m *AddRolesForEmpsResponse) String() string            { return proto.CompactTextString(m) }
func (*AddRolesForEmpsResponse) ProtoMessage()               {}
func (*AddRolesForEmpsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *AddRolesForEmpsResponse) GetDingtalkCorpRoleAddrolesforempsResponse() *AddRolesForEmps {
	if m != nil {
		return m.DingtalkCorpRoleAddrolesforempsResponse
	}
	return nil
}

func (m *AddRolesForEmpsResponse) GetErrorResponse() *TopApiResponse {
	if m != nil {
		return m.ErrorResponse
	}
	return nil
}

// 批量删除员工角的色信息请求参数
type RemoveRolesForEmpsRequest struct {
	// 角色标签id
	RoleidList []string `protobuf:"bytes,1,rep,name=roleid_list,json=roleidList" json:"roleid_list,omitempty"`
	// 用户userid
	UseridList []string `protobuf:"bytes,2,rep,name=userid_list,json=useridList" json:"userid_list,omitempty"`
}

func (m *RemoveRolesForEmpsRequest) Reset()                    { *m = RemoveRolesForEmpsRequest{} }
func (m *RemoveRolesForEmpsRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveRolesForEmpsRequest) ProtoMessage()               {}
func (*RemoveRolesForEmpsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *RemoveRolesForEmpsRequest) GetRoleidList() []string {
	if m != nil {
		return m.RoleidList
	}
	return nil
}

func (m *RemoveRolesForEmpsRequest) GetUseridList() []string {
	if m != nil {
		return m.UseridList
	}
	return nil
}

type RemoveRolesForEmps struct {
	Result *DingOpenResponse `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *RemoveRolesForEmps) Reset()                    { *m = RemoveRolesForEmps{} }
func (m *RemoveRolesForEmps) String() string            { return proto.CompactTextString(m) }
func (*RemoveRolesForEmps) ProtoMessage()               {}
func (*RemoveRolesForEmps) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *RemoveRolesForEmps) GetResult() *DingOpenResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

// 批量删除员工角的色信息响应参数
type RemoveRolesForEmpsResponse struct {
	DingtalkCorpRoleRemoverolesforempsResponse *RemoveRolesForEmps `protobuf:"bytes,1,opt,name=dingtalk_corp_role_removerolesforemps_response,json=dingtalkCorpRoleRemoverolesforempsResponse" json:"dingtalk_corp_role_removerolesforemps_response,omitempty"`
	ErrorResponse                              *TopApiResponse     `protobuf:"bytes,2,opt,name=error_response,json=errorResponse" json:"error_response,omitempty"`
}

func (m *RemoveRolesForEmpsResponse) Reset()                    { *m = RemoveRolesForEmpsResponse{} }
func (m *RemoveRolesForEmpsResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveRolesForEmpsResponse) ProtoMessage()               {}
func (*RemoveRolesForEmpsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *RemoveRolesForEmpsResponse) GetDingtalkCorpRoleRemoverolesforempsResponse() *RemoveRolesForEmps {
	if m != nil {
		return m.DingtalkCorpRoleRemoverolesforempsResponse
	}
	return nil
}

func (m *RemoveRolesForEmpsResponse) GetErrorResponse() *TopApiResponse {
	if m != nil {
		return m.ErrorResponse
	}
	return nil
}

// 删除角色信息请求参数
type DeleteRoleRequest struct {
	// 角色id
	RoleId int64 `protobuf:"varint,1,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
}

func (m *DeleteRoleRequest) Reset()                    { *m = DeleteRoleRequest{} }
func (m *DeleteRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRoleRequest) ProtoMessage()               {}
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *DeleteRoleRequest) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type DeleteRole struct {
	Result *DingOpenResponse `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *DeleteRole) Reset()                    { *m = DeleteRole{} }
func (m *DeleteRole) String() string            { return proto.CompactTextString(m) }
func (*DeleteRole) ProtoMessage()               {}
func (*DeleteRole) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *DeleteRole) GetResult() *DingOpenResponse {
	if m != nil {
		return m.Result
	}
	return nil
}

// 删除角色信息响应参数
type DeleteRoleResponse struct {
	DingtalkCorpRoleDeleteroleResponse *DeleteRole     `protobuf:"bytes,1,opt,name=dingtalk_corp_role_deleterole_response,json=dingtalkCorpRoleDeleteroleResponse" json:"dingtalk_corp_role_deleterole_response,omitempty"`
	ErrorResponse                      *TopApiResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse" json:"error_response,omitempty"`
}

func (m *DeleteRoleResponse) Reset()                    { *m = DeleteRoleResponse{} }
func (m *DeleteRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteRoleResponse) ProtoMessage()               {}
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

func (m *DeleteRoleResponse) GetDingtalkCorpRoleDeleteroleResponse() *DeleteRole {
	if m != nil {
		return m.DingtalkCorpRoleDeleteroleResponse
	}
	return nil
}

func (m *DeleteRoleResponse) GetErrorResponse() *TopApiResponse {
	if m != nil {
		return m.ErrorResponse
	}
	return nil
}

// 获取角色组信息请求参数
type GetRoleGroupRequest struct {
	// 角色组的id
	GroupId int64 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
}

func (m *GetRoleGroupRequest) Reset()                    { *m = GetRoleGroupRequest{} }
func (m *GetRoleGroupRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRoleGroupRequest) ProtoMessage()               {}
func (*GetRoleGroupRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *GetRoleGroupRequest) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type RoleGroupRolesOpenRole struct {
	RoleId   int64  `protobuf:"varint,1,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
	RoleName string `protobuf:"bytes,2,opt,name=role_name,json=roleName" json:"role_name,omitempty"`
}

func (m *RoleGroupRolesOpenRole) Reset()                    { *m = RoleGroupRolesOpenRole{} }
func (m *RoleGroupRolesOpenRole) String() string            { return proto.CompactTextString(m) }
func (*RoleGroupRolesOpenRole) ProtoMessage()               {}
func (*RoleGroupRolesOpenRole) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *RoleGroupRolesOpenRole) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RoleGroupRolesOpenRole) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type RoleGroupRoles struct {
	OpenRole []*RoleGroupRolesOpenRole `protobuf:"bytes,1,rep,name=open_role,json=openRole" json:"open_role,omitempty"`
}

func (m *RoleGroupRoles) Reset()                    { *m = RoleGroupRoles{} }
func (m *RoleGroupRoles) String() string            { return proto.CompactTextString(m) }
func (*RoleGroupRoles) ProtoMessage()               {}
func (*RoleGroupRoles) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *RoleGroupRoles) GetOpenRole() []*RoleGroupRolesOpenRole {
	if m != nil {
		return m.OpenRole
	}
	return nil
}

type RoleGroup struct {
	GroupName string          `protobuf:"bytes,1,opt,name=group_name,json=groupName" json:"group_name,omitempty"`
	Roles     *RoleGroupRoles `protobuf:"bytes,2,opt,name=roles" json:"roles,omitempty"`
}

func (m *RoleGroup) Reset()                    { *m = RoleGroup{} }
func (m *RoleGroup) String() string            { return proto.CompactTextString(m) }
func (*RoleGroup) ProtoMessage()               {}
func (*RoleGroup) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *RoleGroup) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *RoleGroup) GetRoles() *RoleGroupRoles {
	if m != nil {
		return m.Roles
	}
	return nil
}

type GetRoleGroupBody struct {
	DingOpenErrcode int64      `protobuf:"varint,1,opt,name=ding_open_errcode,json=dingOpenErrcode" json:"ding_open_errcode,omitempty"`
	RoleGroup       *RoleGroup `protobuf:"bytes,2,opt,name=role_group,json=roleGroup" json:"role_group,omitempty"`
	ErrorMsg        string     `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg" json:"error_msg,omitempty"`
	Success         bool       `protobuf:"varint,4,opt,name=success" json:"success,omitempty"`
}

func (m *GetRoleGroupBody) Reset()                    { *m = GetRoleGroupBody{} }
func (m *GetRoleGroupBody) String() string            { return proto.CompactTextString(m) }
func (*GetRoleGroupBody) ProtoMessage()               {}
func (*GetRoleGroupBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *GetRoleGroupBody) GetDingOpenErrcode() int64 {
	if m != nil {
		return m.DingOpenErrcode
	}
	return 0
}

func (m *GetRoleGroupBody) GetRoleGroup() *RoleGroup {
	if m != nil {
		return m.RoleGroup
	}
	return nil
}

func (m *GetRoleGroupBody) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *GetRoleGroupBody) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetRoleGroup struct {
	Result *GetRoleGroupBody `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *GetRoleGroup) Reset()                    { *m = GetRoleGroup{} }
func (m *GetRoleGroup) String() string            { return proto.CompactTextString(m) }
func (*GetRoleGroup) ProtoMessage()               {}
func (*GetRoleGroup) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{29} }

func (m *GetRoleGroup) GetResult() *GetRoleGroupBody {
	if m != nil {
		return m.Result
	}
	return nil
}

// 获取角色组信息响应参数
type GetRoleGroupResponse struct {
	DingtalkCorpRoleGetrolegroupResponse *GetRoleGroup   `protobuf:"bytes,1,opt,name=dingtalk_corp_role_getrolegroup_response,json=dingtalkCorpRoleGetrolegroupResponse" json:"dingtalk_corp_role_getrolegroup_response,omitempty"`
	ErrorResponse                        *TopApiResponse `protobuf:"bytes,2,opt,name=error_response,json=errorResponse" json:"error_response,omitempty"`
}

func (m *GetRoleGroupResponse) Reset()                    { *m = GetRoleGroupResponse{} }
func (m *GetRoleGroupResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRoleGroupResponse) ProtoMessage()               {}
func (*GetRoleGroupResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{30} }

func (m *GetRoleGroupResponse) GetDingtalkCorpRoleGetrolegroupResponse() *GetRoleGroup {
	if m != nil {
		return m.DingtalkCorpRoleGetrolegroupResponse
	}
	return nil
}

func (m *GetRoleGroupResponse) GetErrorResponse() *TopApiResponse {
	if m != nil {
		return m.ErrorResponse
	}
	return nil
}

// 获取角色详情请求参数
type GetRoleRequest struct {
	// 角色id
	RoleId int64 `protobuf:"varint,1,opt,name=roleId" json:"roleId,omitempty"`
}

func (m *GetRoleRequest) Reset()                    { *m = GetRoleRequest{} }
func (m *GetRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRoleRequest) ProtoMessage()               {}
func (*GetRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{31} }

func (m *GetRoleRequest) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type GetRole struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	GroupId int64  `protobuf:"varint,2,opt,name=groupId" json:"groupId,omitempty"`
}

func (m *GetRole) Reset()                    { *m = GetRole{} }
func (m *GetRole) String() string            { return proto.CompactTextString(m) }
func (*GetRole) ProtoMessage()               {}
func (*GetRole) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{32} }

func (m *GetRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetRole) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type GetRoleResponseBody struct {
	Role    *GetRole `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Errcode int64    `protobuf:"varint,2,opt,name=errcode" json:"errcode,omitempty"`
	Errmsg  string   `protobuf:"bytes,3,opt,name=errmsg" json:"errmsg,omitempty"`
}

func (m *GetRoleResponseBody) Reset()                    { *m = GetRoleResponseBody{} }
func (m *GetRoleResponseBody) String() string            { return proto.CompactTextString(m) }
func (*GetRoleResponseBody) ProtoMessage()               {}
func (*GetRoleResponseBody) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{33} }

func (m *GetRoleResponseBody) GetRole() *GetRole {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *GetRoleResponseBody) GetErrcode() int64 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *GetRoleResponseBody) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

// 获取角色详情响应参数
type GetRoleResponse struct {
	DingtalkOapiRoleGetroleResponse *GetRoleResponseBody `protobuf:"bytes,1,opt,name=dingtalk_oapi_role_getrole_response,json=dingtalkOapiRoleGetroleResponse" json:"dingtalk_oapi_role_getrole_response,omitempty"`
}

func (m *GetRoleResponse) Reset()                    { *m = GetRoleResponse{} }
func (m *GetRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRoleResponse) ProtoMessage()               {}
func (*GetRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{34} }

func (m *GetRoleResponse) GetDingtalkOapiRoleGetroleResponse() *GetRoleResponseBody {
	if m != nil {
		return m.DingtalkOapiRoleGetroleResponse
	}
	return nil
}

func init() {
	proto.RegisterType((*RoleSimplelistRequest)(nil), "tapi.RoleSimplelistRequest")
	proto.RegisterType((*RoleSimplelistResponseResultListEmpSimpleList)(nil), "tapi.RoleSimplelistResponseResultListEmpSimpleList")
	proto.RegisterType((*RoleSimplelistResponseResultList)(nil), "tapi.RoleSimplelistResponseResultList")
	proto.RegisterType((*RoleSimplelistResponseResult)(nil), "tapi.RoleSimplelistResponseResult")
	proto.RegisterType((*RoleSimplelist)(nil), "tapi.RoleSimplelist")
	proto.RegisterType((*RoleSimplelistResponse)(nil), "tapi.RoleSimplelistResponse")
	proto.RegisterType((*RoleListRequest)(nil), "tapi.RoleListRequest")
	proto.RegisterType((*RoleListResultListRoleGroupsRolesBody)(nil), "tapi.RoleListResultListRoleGroupsRolesBody")
	proto.RegisterType((*RoleListResultListRoleGroupsRoles)(nil), "tapi.RoleListResultListRoleGroupsRoles")
	proto.RegisterType((*RoleListResultListRoleGroups)(nil), "tapi.RoleListResultListRoleGroups")
	proto.RegisterType((*RoleListResultList)(nil), "tapi.RoleListResultList")
	proto.RegisterType((*RoleListResult)(nil), "tapi.RoleListResult")
	proto.RegisterType((*RoleList)(nil), "tapi.RoleList")
	proto.RegisterType((*RoleListResponse)(nil), "tapi.RoleListResponse")
	proto.RegisterType((*AddRolesForEmpsRequest)(nil), "tapi.AddRolesForEmpsRequest")
	proto.RegisterType((*DingOpenResponse)(nil), "tapi.DingOpenResponse")
	proto.RegisterType((*AddRolesForEmps)(nil), "tapi.AddRolesForEmps")
	proto.RegisterType((*AddRolesForEmpsResponse)(nil), "tapi.AddRolesForEmpsResponse")
	proto.RegisterType((*RemoveRolesForEmpsRequest)(nil), "tapi.RemoveRolesForEmpsRequest")
	proto.RegisterType((*RemoveRolesForEmps)(nil), "tapi.RemoveRolesForEmps")
	proto.RegisterType((*RemoveRolesForEmpsResponse)(nil), "tapi.RemoveRolesForEmpsResponse")
	proto.RegisterType((*DeleteRoleRequest)(nil), "tapi.DeleteRoleRequest")
	proto.RegisterType((*DeleteRole)(nil), "tapi.DeleteRole")
	proto.RegisterType((*DeleteRoleResponse)(nil), "tapi.DeleteRoleResponse")
	proto.RegisterType((*GetRoleGroupRequest)(nil), "tapi.GetRoleGroupRequest")
	proto.RegisterType((*RoleGroupRolesOpenRole)(nil), "tapi.RoleGroupRolesOpenRole")
	proto.RegisterType((*RoleGroupRoles)(nil), "tapi.RoleGroupRoles")
	proto.RegisterType((*RoleGroup)(nil), "tapi.RoleGroup")
	proto.RegisterType((*GetRoleGroupBody)(nil), "tapi.GetRoleGroupBody")
	proto.RegisterType((*GetRoleGroup)(nil), "tapi.GetRoleGroup")
	proto.RegisterType((*GetRoleGroupResponse)(nil), "tapi.GetRoleGroupResponse")
	proto.RegisterType((*GetRoleRequest)(nil), "tapi.GetRoleRequest")
	proto.RegisterType((*GetRole)(nil), "tapi.GetRole")
	proto.RegisterType((*GetRoleResponseBody)(nil), "tapi.GetRoleResponseBody")
	proto.RegisterType((*GetRoleResponse)(nil), "tapi.GetRoleResponse")
}

func init() { proto.RegisterFile("role.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xed, 0x6e, 0x1b, 0x45,
	0x17, 0xd6, 0xda, 0x7e, 0x63, 0xef, 0x71, 0x62, 0xa7, 0xf3, 0xa6, 0xae, 0x53, 0x52, 0x25, 0x59,
	0xa0, 0xb5, 0xd2, 0x60, 0x50, 0xfa, 0x03, 0x28, 0x14, 0xc9, 0x34, 0x21, 0xaa, 0x48, 0x5b, 0x69,
	0x88, 0x2a, 0x15, 0x8a, 0x56, 0x8b, 0x77, 0xe2, 0x6c, 0xbb, 0xeb, 0x59, 0x66, 0xd6, 0x48, 0x54,
	0x95, 0xb8, 0x1a, 0x84, 0xc4, 0x0d, 0xf0, 0x93, 0x0b, 0xe0, 0x02, 0xb8, 0x1d, 0x34, 0x1f, 0xfb,
	0x35, 0x5e, 0xe7, 0x43, 0xf2, 0xaf, 0x78, 0x66, 0xcf, 0x3c, 0xe7, 0xcc, 0x73, 0x9e, 0x73, 0xce,
	0x04, 0x80, 0xd1, 0x90, 0x0c, 0x63, 0x46, 0x13, 0x8a, 0x1a, 0x89, 0x17, 0x07, 0xb7, 0x57, 0xc7,
	0x34, 0x8a, 0xe8, 0x54, 0xed, 0x39, 0xaf, 0xe0, 0x26, 0xa6, 0x21, 0xf9, 0x2e, 0x88, 0xe2, 0x90,
	0x84, 0x01, 0x4f, 0x30, 0xf9, 0x79, 0x46, 0x78, 0x82, 0x6e, 0x41, 0x53, 0x1c, 0x75, 0x03, 0xbf,
	0x6f, 0xed, 0x58, 0x83, 0x3a, 0x5e, 0x11, 0xcb, 0x27, 0x3e, 0x42, 0xd0, 0xe0, 0xc1, 0x5b, 0xd2,
	0xaf, 0xc9, 0x5d, 0xf9, 0x1b, 0xf5, 0x60, 0x85, 0x9e, 0x9d, 0x71, 0x92, 0xf4, 0xeb, 0xca, 0x56,
	0xad, 0x9c, 0x63, 0xf8, 0xc8, 0x44, 0xe7, 0x31, 0x9d, 0x72, 0x82, 0x09, 0x9f, 0x85, 0xc9, 0x49,
	0xc0, 0x93, 0xa3, 0x28, 0x56, 0x9f, 0xc5, 0x42, 0x00, 0xcd, 0x38, 0x61, 0xda, 0xa9, 0x8d, 0xf5,
	0xca, 0xf9, 0x0d, 0x76, 0x2e, 0x03, 0x42, 0x3f, 0x40, 0x97, 0x44, 0xb1, 0xcb, 0xa5, 0x8d, 0x2b,
	0x8c, 0xfa, 0xd6, 0x4e, 0x7d, 0xd0, 0x3e, 0x78, 0x30, 0x14, 0x17, 0x1f, 0x5e, 0x2b, 0x12, 0xbc,
	0x46, 0x8a, 0x4b, 0x67, 0x06, 0x5b, 0x17, 0x9d, 0x47, 0x9b, 0xd0, 0x3a, 0xf7, 0xb8, 0x1b, 0x51,
	0x46, 0x64, 0xe8, 0x2d, 0xdc, 0x3c, 0xf7, 0xf8, 0x53, 0xca, 0x08, 0x7a, 0x08, 0x0d, 0x19, 0x8c,
	0x20, 0xac, 0x7d, 0x70, 0xf7, 0x6a, 0xc1, 0x60, 0x79, 0xc6, 0x39, 0x81, 0x4e, 0xd9, 0x12, 0x3d,
	0x84, 0x15, 0x26, 0xad, 0xa4, 0x9b, 0xf6, 0x81, 0x73, 0x39, 0x1e, 0xd6, 0x27, 0x9c, 0xbf, 0x2d,
	0xe8, 0x55, 0x1b, 0xa2, 0x73, 0xb8, 0xeb, 0x07, 0xd3, 0x49, 0xe2, 0x85, 0x6f, 0xdc, 0x31, 0x65,
	0xb1, 0x2b, 0x93, 0xcf, 0x33, 0x43, 0x97, 0x69, 0x4b, 0xed, 0x76, 0xa3, 0xd2, 0xad, 0x93, 0x62,
	0x3c, 0xa6, 0x2c, 0x5e, 0xe0, 0xe9, 0x0b, 0xe8, 0x10, 0xc6, 0x28, 0xcb, 0x11, 0x6b, 0x45, 0xc4,
	0x53, 0x1a, 0x8f, 0xe2, 0x20, 0xbb, 0xc0, 0x9a, 0xb4, 0x4d, 0x97, 0xce, 0x23, 0xe8, 0x0a, 0xd8,
	0x93, 0x82, 0x50, 0x53, 0x3d, 0x5a, 0x95, 0x7a, 0xac, 0x95, 0xf4, 0x78, 0x0a, 0x1f, 0xe6, 0xc7,
	0x33, 0xaa, 0x69, 0x48, 0x8e, 0x19, 0x9d, 0xc5, 0x5c, 0xfc, 0xe2, 0x5f, 0x53, 0xff, 0x57, 0xd4,
	0x81, 0x5a, 0x26, 0xfc, 0x5a, 0xe0, 0xa3, 0xf7, 0xc0, 0x96, 0x84, 0x4c, 0xbd, 0x48, 0xc5, 0x6b,
	0xe3, 0x96, 0xd8, 0x78, 0xe6, 0x45, 0xc4, 0x39, 0x83, 0xdd, 0x4b, 0x51, 0xd1, 0x08, 0xfe, 0x27,
	0x0e, 0x70, 0xad, 0xc9, 0xfb, 0x39, 0x7f, 0x97, 0x46, 0x83, 0xd5, 0x49, 0xe7, 0x9d, 0xd2, 0xe0,
	0x22, 0x7b, 0xf4, 0x28, 0x77, 0x21, 0x08, 0xbd, 0x77, 0x45, 0x17, 0x1a, 0x1e, 0xdd, 0x01, 0x98,
	0x88, 0xdd, 0xe2, 0x25, 0x6d, 0xb9, 0x23, 0x6f, 0xf9, 0x12, 0xd0, 0x3c, 0x14, 0x7a, 0x0c, 0x6d,
	0x49, 0x8c, 0xb4, 0x4b, 0x2f, 0xe7, 0x5c, 0xc1, 0xb3, 0x6c, 0x4c, 0xea, 0xb7, 0xf3, 0x52, 0xa9,
	0x3c, 0xb7, 0x9d, 0x2b, 0x27, 0x3b, 0x2f, 0xa7, 0xfd, 0x52, 0x39, 0xf5, 0x17, 0xba, 0x52, 0x05,
	0xf4, 0x19, 0xb4, 0xd2, 0x6f, 0x68, 0xdf, 0x28, 0x9d, 0x8d, 0xaa, 0xb3, 0x59, 0xb1, 0xfc, 0x61,
	0xc1, 0x7a, 0xe1, 0x93, 0x12, 0xef, 0x0b, 0xd8, 0xa9, 0x28, 0x93, 0xaa, 0x02, 0xe9, 0x18, 0xe0,
	0x5b, 0x66, 0x69, 0x9c, 0x2c, 0xad, 0x28, 0x5e, 0x41, 0x6f, 0xe4, 0xfb, 0x32, 0x97, 0xdf, 0x50,
	0x76, 0x14, 0xc5, 0x3c, 0xad, 0x8d, 0x5d, 0x58, 0x15, 0x01, 0x86, 0x81, 0x9f, 0xf7, 0xc3, 0x3a,
	0x6e, 0xeb, 0x3d, 0x49, 0xca, 0x36, 0xb4, 0x55, 0x8f, 0x75, 0x35, 0xab, 0xf5, 0x81, 0x8d, 0x41,
	0x6d, 0xe9, 0xce, 0xb7, 0x7e, 0x18, 0x4c, 0x27, 0xcf, 0x63, 0x32, 0xcd, 0xc2, 0xdd, 0x83, 0x1b,
	0xe2, 0x3a, 0x2e, 0x8d, 0xc9, 0xd4, 0x25, 0x8c, 0x8d, 0xa9, 0x9f, 0x16, 0x60, 0xd7, 0xd7, 0xc6,
	0x47, 0x6a, 0x5b, 0x94, 0x8e, 0xba, 0x5a, 0xc4, 0x27, 0x69, 0xe9, 0xc8, 0x8d, 0xa7, 0x7c, 0x82,
	0xfa, 0xd0, 0xe4, 0xb3, 0xf1, 0x98, 0x70, 0x2e, 0x27, 0x47, 0x0b, 0xa7, 0x4b, 0x67, 0x04, 0x5d,
	0xe3, 0x52, 0x68, 0x68, 0xe4, 0xaf, 0xa7, 0xc8, 0x31, 0xa3, 0xcb, 0x32, 0xf8, 0x8f, 0x05, 0xb7,
	0xe6, 0x88, 0xd1, 0x37, 0xe0, 0x70, 0xbf, 0x22, 0x91, 0x9e, 0xef, 0xcb, 0x5a, 0x38, 0xa3, 0x8c,
	0x44, 0x31, 0x37, 0x73, 0x7a, 0x53, 0x39, 0x34, 0x31, 0xef, 0x99, 0xa9, 0x1d, 0x95, 0x61, 0x96,
	0x93, 0xe5, 0x1f, 0x61, 0x13, 0x93, 0x88, 0xfe, 0x42, 0xaa, 0x12, 0xbd, 0xad, 0xca, 0xb0, 0x98,
	0x67, 0x5b, 0x95, 0xd8, 0x55, 0xd3, 0x7c, 0x08, 0x68, 0x1e, 0xfe, 0xda, 0x94, 0xff, 0x6b, 0xc1,
	0xed, 0xaa, 0x28, 0x35, 0x01, 0xef, 0x60, 0x58, 0xc1, 0x3a, 0x93, 0x07, 0x2e, 0x22, 0x3e, 0xad,
	0xf2, 0x79, 0xe4, 0x3d, 0x93, 0x7b, 0x3c, 0x07, 0xb6, 0x1c, 0xfa, 0xf7, 0xe1, 0xc6, 0x21, 0x09,
	0x49, 0x42, 0x94, 0x93, 0x8b, 0x1f, 0x49, 0xce, 0x97, 0x00, 0xb9, 0xf5, 0xb5, 0x59, 0xfc, 0xcb,
	0x02, 0x54, 0x74, 0xa6, 0xe3, 0xf7, 0x2b, 0x67, 0xb4, 0x2f, 0x0d, 0x35, 0x91, 0x25, 0xd6, 0xd6,
	0xb5, 0x9b, 0x1c, 0x69, 0x6e, 0x3e, 0x1f, 0x66, 0x87, 0x97, 0xc3, 0xd2, 0x27, 0xf0, 0xff, 0x63,
	0x92, 0xb7, 0xf9, 0x94, 0xa7, 0x4d, 0x68, 0xa9, 0xd1, 0x92, 0x11, 0xd5, 0x94, 0xeb, 0x27, 0xbe,
	0xf3, 0x4c, 0x3d, 0x49, 0x94, 0xb9, 0xc8, 0x9a, 0x64, 0x44, 0xb0, 0xb6, 0xf0, 0x05, 0x7a, 0xe1,
	0x30, 0xfe, 0x56, 0xcd, 0x92, 0x1c, 0x0f, 0x7d, 0x0e, 0xb6, 0xec, 0x53, 0xc2, 0x44, 0x0f, 0xa8,
	0xad, 0xbc, 0x39, 0xcf, 0x3b, 0xc6, 0x2d, 0xaa, 0x7f, 0x39, 0x2f, 0xc0, 0xce, 0x6c, 0x8c, 0xf9,
	0x68, 0x19, 0xf3, 0x11, 0xed, 0xa5, 0xd3, 0xb7, 0x66, 0x0e, 0x97, 0xdc, 0x45, 0x3a, 0xc9, 0x7f,
	0xb7, 0x60, 0xbd, 0xc8, 0x93, 0x7c, 0x73, 0x5c, 0xa7, 0xa9, 0x0e, 0xd5, 0xc3, 0x5e, 0x8d, 0x5d,
	0xed, 0xb1, 0x6b, 0x7a, 0xb4, 0xb3, 0x11, 0x5b, 0x6e, 0xc2, 0xf5, 0xc5, 0x4d, 0xb8, 0x51, 0x6e,
	0xc2, 0x5f, 0xc1, 0x6a, 0x31, 0xcc, 0x45, 0x42, 0x36, 0xaf, 0x52, 0x7c, 0x70, 0x6e, 0x94, 0xf5,
	0xa0, 0x45, 0xf6, 0x1a, 0x06, 0x15, 0x52, 0x9e, 0x90, 0x44, 0xfc, 0x55, 0x2c, 0x1b, 0x62, 0x46,
	0xf3, 0xae, 0xf0, 0x07, 0xa6, 0x9c, 0x8f, 0x0b, 0x00, 0xcb, 0x11, 0xf4, 0x00, 0x3a, 0xda, 0x65,
	0xaa, 0xe5, 0x1e, 0x68, 0x1d, 0x1a, 0x25, 0xff, 0x29, 0x34, 0xb5, 0xa5, 0x78, 0x92, 0x16, 0x34,
	0x22, 0x7f, 0x0b, 0x92, 0xb5, 0xe4, 0xf5, 0x9b, 0x34, 0xab, 0x80, 0xd7, 0x59, 0xcd, 0xa4, 0x5e,
	0xa5, 0x1c, 0x76, 0xa1, 0xa1, 0x15, 0x2b, 0x82, 0x5d, 0x2b, 0x5d, 0x1f, 0xcb, 0x4f, 0x02, 0x33,
	0xd5, 0x89, 0xc6, 0xd4, 0x4b, 0x11, 0x24, 0x61, 0x2c, 0x4f, 0xb6, 0x5e, 0x39, 0x6f, 0xa1, 0x6b,
	0xf8, 0x42, 0x13, 0x78, 0x3f, 0x4b, 0x05, 0xf5, 0xe2, 0xa0, 0x94, 0x0a, 0x33, 0x0b, 0x9b, 0xe5,
	0x30, 0x0a, 0xf1, 0xe2, 0xed, 0x14, 0xe5, 0xb9, 0x17, 0x07, 0x85, 0x64, 0x64, 0x46, 0x77, 0xbe,
	0x6f, 0xcb, 0xff, 0x39, 0xf9, 0xc7, 0x02, 0xe3, 0xcf, 0xda, 0x9a, 0xe8, 0x7f, 0xa7, 0x5e, 0xf8,
	0x66, 0x78, 0xea, 0xc5, 0xc1, 0x4f, 0x2b, 0xf2, 0xe3, 0x83, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x18, 0x50, 0xe5, 0xb5, 0xb2, 0x0e, 0x00, 0x00,
}
